# Generated by Django 4.1.13 on 2023-12-08 13:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='primary_bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='secondary_bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
