# Generated by Django 4.1.13 on 2023-12-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='title',
            new_name='mame',
        ),
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
