# Generated by Django 4.1.13 on 2023-12-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0004_delete_skills_rename_title_projects_mame_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='mame',
            new_name='name',
        ),
    ]
