# Generated by Django 4.1.13 on 2023-12-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0006_alter_projects_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('GAMES', 'GAMES'), ('WEBSITE', 'WEBSITE'), ('APP', 'APP')], default='GAMES', max_length=50),
            preserve_default=False,
        ),
    ]
