# Generated by Django 4.1.13 on 2023-12-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0007_projects_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('GAME', 'GAME'), ('WEBSITE', 'WEBSITE'), ('APP', 'APP')], max_length=50),
        ),
    ]
