# Generated by Django 4.1.13 on 2024-01-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0010_alter_projects_options_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/preview/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/thumbnail/'),
        ),
    ]
